### ISSUE TITLE
Program doesn't seem to support full paths

### ISSUE THREAD

**Issue by InternalLoss** [Qubits01/xbox_shrinker#2]
When trying to provide a full path, such as `"F:\Games\DIC(UI) Dumps\XBOX\25TL\SEP13011042072.iso"`, the program errors and states the file cannot be found.

```
F:\Microsoft\Xbox\Tools\PC>xbox_shrinker.exe "F:\Games\DIC(UI) Dumps\XBOX\25TL\SEP13011042072.iso"
Error. File not found: SEP13011042072.iso
```

**Comment by Qubits01** [comment]
hopefully fixed.
Hope I didn't overlook anything that was affected by the changes
