### ISSUE TITLE
Confused on usage

### ISSUE THREAD

**Issue by updawg** [Qubits01/xbox_shrinker#3]
What does scrubbing the padding get you over directly converting the redump style ISOs to the XISO format? Is it just to be able to store them in a compressed format more efficiently and then be able to convert them back to a redump standard? 

Or is the process redump iso -> xbox_shrinker -> shrinked iso -> redump2xiso -> shrinked xiso

Thanks!

**Comment by Qubits01** [comment]
Exactly. There are people who want to, let's call it ideological reasons, have perfectly preserved images of games, meaning 1:1 backups with the video partition and the original random padding. Or at least a possibility to revert back to the original format. Similar to wux, nkit etc.
Especially with xbox you can save around 70% of total space by scrubbing which is substantial (close to 10TB saved for the full redump set).

The process you decribe is correct for creating a scrubbed xiso.

**Comment by updawg** [comment]
I guess the question I am trying to ask more specifically is does scrubbing and zipping save more space then converting to XISO directly? Thanks!

**Comment by Qubits01** [comment]
Unscrubbed and zipped, XISOs and redump ISOs are almost the same size. The difference is the missing video partition, but it compresses very well to about 10MB. So the size difference unscrubbed and zipped is only around 10MB.

Space saved by scrubbing varies a lot depending on the game, but on average several Gigabytes are saved per game by scrubbing.
Scrubbing only affects the game partition. This partition is identical for XISO and redump ISO so the amount saved by scrubbing is also identical.

So short answer to your question: space saved by converting to XISO is neglectable compared to scrubbing.

**Comment by updawg** [comment]
I appreciate the comment - I guess where my confusion arises is I was thinking of unpacked XISO and not XISO in iso format. Thanks for your hard work!
